const quotes  = [
  "The best way to predict the future is to create it. — Peter Drucker",
  "Success is not final, failure is not fatal: it is the courage to continue that counts. — Winston Churchill",
  "It always seems impossible until it's done. — Nelson Mandela",
  "Whether you think you can or you think you can't, you're right. — Henry Ford",
  "Do what you can, with what you have, where you are. — Theodore Roosevelt",
  "The future depends on what you do today. — Mahatma Gandhi",
  "Dream big and dare to fail. — Norman Vaughan",
  "The only limit to our realization of tomorrow is our doubts of today. — Franklin D. Roosevelt",
  "Action is the foundational key to all success. — Pablo Picasso",
  "If opportunity doesn't knock, build a door. — Milton Berle",
  "Stay hungry. Stay foolish. — Steve Jobs",
  "The harder I work, the luckier I get. — Samuel Goldwyn",
  "Discipline is choosing between what you want now and what you want most. — Commonly attributed to Abraham Lincoln",
  "Don't watch the clock; do what it does. Keep going. — Sam Levenson",
  "The secret of getting ahead is getting started. — Mark Twain",
  "The journey of a thousand miles begins with one step. — Lao Tzu",
  "Fall seven times, stand up eight. — Japanese Proverb",
  "Believe you can and you're halfway there. — Theodore Roosevelt",
  "Everything you've ever wanted is on the other side of fear. — George Addair",
  "Success usually comes to those who are too busy to be looking for it. — Henry David Thoreau",
  "Life is like riding a bicycle. To keep your balance, you must keep moving. — Albert Einstein",
  "A winner is a dreamer who never gives up. — Nelson Mandela",
  "Work hard in silence, let success make the noise. — Frank Ocean",
  "The expert in anything was once a beginner. — Helen Hayes",
  "You miss 100% of the shots you don't take. — Wayne Gretzky",
  "The only place where success comes before work is in the dictionary. — Vidal Sassoon",
  "Your time is limited, so don't waste it living someone else's life. — Steve Jobs",
  "Nothing will work unless you do. — Maya Angelou",
  "The future belongs to those who believe in the beauty of their dreams. — Eleanor Roosevelt",
  "Great things never come from comfort zones. — Roy T. Bennett",
  "Never let the fear of striking out keep you from playing the game. — Babe Ruth",
  "The man who moves a mountain begins by carrying away small stones. — Confucius",
  "Success is walking from failure to failure with no loss of enthusiasm. — Winston Churchill",
  "The only impossible journey is the one you never begin. — Tony Robbins",
  "Done is better than perfect. — Sheryl Sandberg",
  "Motivation gets you going, but discipline keeps you growing. — John C. Maxwell",
  "Small disciplines repeated with consistency every day lead to great achievements. — John C. Maxwell",
  "Don't count the days, make the days count. — Muhammad Ali",
  "Energy and persistence conquer all things. — Benjamin Franklin",
  "The difference between ordinary and extraordinary is that little extra. — Jimmy Johnson"
];
const fonts = [
  "Consolas",
  "Cascadia Code",
  "Cascadia Mono",
  "Fira Code",
  "JetBrains Mono",
  "Source Code Pro",
  "IBM Plex Mono",
  "Roboto Mono",
  "Ubuntu Mono",
  "Inconsolata",
  "Victor Mono",
  "Monaspace Neon",
  "Monaspace Argon",
  "Monaspace Krypton",
  "Monaspace Radon",
  "Monaspace Xenon",
  "Hack",
  "Anonymous Pro",
  "PT Mono",
  "Space Mono",
  "Overpass Mono",
  "Courier New",
  "Menlo",
  "Monaco",
  "SF Mono",
  "Dank Mono",
  "Iosevka",
  "Cousine",
  "DejaVu Sans Mono",
  "Liberation Mono",
  "Noto Sans Mono",
  "PragmataPro",
  "Input Mono",
  "Operator Mono",
  "Commit Mono",
  "Recursive Mono",
  "Intel One Mono",
  "Envy Code R",
  "CaskaydiaCove Nerd Font",
  "MesloLGS NF"
];
const colorss = [
  "#FF0000",
  "#00FF00",
  "#0000FF",
  "#FFFF00",
  "#FF00FF",
  "#00FFFF",
  "#FFA500",
  "#800080",
  "#FFC0CB",
  "#A52A2A",
  "#808080",
  "#000000",
  "#FFFFFF",
  "#4CAF50",
  "#2196F3",
  "#F44336",
  "#FF9800",
  "#9C27B0",
  "#3F51B5",
  "#009688",
  "#795548",
  "#607D8B",
  "#E91E63",
  "#CDDC39",
  "#8BC34A",
  "#673AB7",
  "#03A9F4",
  "#00BCD4",
  "#FF5722",
  "#FFC107",
  "#C2185B",
  "#7B1FA2",
  "#1976D2",
  "#388E3C",
  "#D32F2F",
  "#F57C00",
  "#512DA8",
  "#455A64",
  "#2E7D32",
  "#B71C1C"
];
const button = document.querySelector("button");
const quote= document.querySelector('h1');
button.addEventListener('click',()=>{
    const index=Math.floor(Math.random()*40);
    quote.textContent =quotes[index];
    quote.style.color =colorss[Math.floor(Math.random()*40)];
    quote.style.fontFamily=fonts[Math.floor(Math.random()*40)]
})